
### CUSTOMERS ### get all customers
GET http://localhost:3000/api/v1/customer/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWMwNzIxNWJhYTAyZDFiODA3MjU5NzYiLCJpYXQiOjE1OTAyMjY1ODEsImV4cCI6MTU5MDIyNjYwMSwiYXVkIjoiQ2xpZW50X0lkZW50aXR5IiwiaXNzIjoiQXV0aG9yaXphdGlvbi9SZXNvdXJjZS9UaGlzIHNlcnZlciIsInN1YiI6InJhdW5AZ21haWwuY29tIn0.pEqqeK2khHPPeJTS8FLeyEFA1MgZ-Z2p_EyR0u5zLp4QQJKI7iGfF0DYkPOD74kqdAXEaCADV9ltsU-Kge6vbg
Username: raun@gmail.com

###CUSTOMERS## update a customer
PUT http://localhost:3000/api/v1/customer/update/5f0a15f74d67874c98a85593/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWMwNzIxNWJhYTAyZDFiODA3MjU5NzYiLCJpYXQiOjE1OTAyMjIyNDUsImV4cCI6MTU5MDIyMjI2NSwiYXVkIjoiQ2xpZW50X0lkZW50aXR5IiwiaXNzIjoiQXV0aG9yaXphdGlvbi9SZXNvdXJjZS9UaGlzIHNlcnZlciIsInN1YiI6InJhdW5AZ21haWwuY29tIn0.yPWde5oZtYMNfmUMmUjJMKE11aEWIIpTIl1u7_1NRJRRBahBeSeWEQcoBWZOHcRjUix5o6d40bv32fq1wGEp2Q
Username: vendor@gmail.com

{
    "customer": {
        "email": "vendor@gmail.com",
        "shippingAddress": {
            "apt_suite_etc": "405",
            "wing": "B"
    }
    }
}

### CUSTOMER ### create a customer
POST http://localhost:3000/api/v1/customer/register
Content-Type: application/json

{
    "customer": {
        "email": "vendor@gmail.com",
        "email_is_verified": false,
        "password": "vendor@123",
		"firstName": "Vendor",
		"lastName": "Singh",
        "society": "5f00bc4db9a01d97f9345ddc",
        "shippingAddress": {
            "apt_suite_etc": "405",
            "wing": "B"
        },
        "state": "5eee00ee8ed1f82cd4e44616",
        "city": "5eee00fb8ed1f82cd4e44617",
        "mobile": "7387191619"
	}
}

### ------------------------------------------------------------------------------------------- ###

### VENDOR ### create a vendor
POST http://localhost:3000/api/v1/vendor/register/
Content-Type: application/json

{
    "vendor": {
        "email": "vendor@gmail.com",
        "email_is_verified": false,
        "companyName": "Vendor Milk",
        "password": "vendor@123",
		"firstName": "Vendor",
		"lastName": "Singh",
        "product": [],
        "mobile": "7387191619",
        "roles": "vendor",
        "permissions": ["read"]
	}
}

### VENDOR ### send vendor feedback
POST http://localhost:3000/api/v1/vendor/feedback
Content-Type: application/json

{
    "vendor": {
        "email": "rishimehta365@gmail.com",
        "name": "Rishi",
		"mobile": "7387191619",
        "subject": "You serve as an exemplary role model by consistently demonstrating a commitment to upholding company values, and encouraging others to do the same."
	}
}

### VENDOR ### get all vendors
GET http://localhost:3000/api/v1/vendor/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVlYzk4ZGM5OThjMTcyMjE5NDU5M2ZkNSIsImlhdCI6MTU5MDI2Nzc4NiwiZXhwIjoxNTkwMjY3ODA2LCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.sYcvGAci6iyZDXyXFV5khdUEA_Lxs72OYTjd3Sobez_kfYMLyaf7ZeiYc2CR312EOlI8Kbv7_7CniWDvXrqMEA
Username: raun@gmail.com


### VENDOR ### get vendor by id
GET http://localhost:3000/api/v1/vendor/5ecd767c64a2050d00e52b2a
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWNkNzY3YzY0YTIwNTBkMDBlNTJiMmEiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkwNTgxMTM0LCJleHAiOjE1OTA1ODExNTQsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.KBekQj8EmeTvZr5ijIxW6LMEzPvS6ya4hbvc5V9UZMIueW3vHaYkIyhsOvXQscWqCgp0dDGXwDXlCKAl-J9aqw
Username: raun@gmail.com


### ------------------------------------------------------------------------------------------- ###

### SOCIETY ### create society
POST http://localhost:3000/api/v1/society/create/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWVkMWE2ZjdmYzE3YjA4MjQwZTlkMDIiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkzODY4MTk2LCJleHAiOjE1OTM4NjgyMTYsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.YQKcgqMW_jhX3Xk1S5M424ur2DuTqCD7uv_ROTe7SaYtvk0Dk2sPfCMSW_r6bWFLzFn87q_gWEfH0J3aHfwqjg
Username: raun@gmail.com

{
    "society": {
        "name": "Blue Ridge",
        "city": "5eee00fb8ed1f82cd4e44617",
        "state": "5eee00ee8ed1f82cd4e44616",
        "vendor": "5ecd767c64a2050d00e52b2a"
	}
}

### SOCIETY ### get all societies
GET http://localhost:3000/api/v1/society?state=5eee00ee8ed1f82cd4e44616&city=5eee00fb8ed1f82cd4e44617
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWVkMWE2ZjdmYzE3YjA4MjQwZTlkMDIiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkyNjU2NjM2LCJleHAiOjE1OTI2NTY2NTYsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.H5Ms9ymsZAsJFlRlo3qF82P0MePlMq1SKzwK7VKHMaXOQZoLZcEzxzLC4r8CbkPiDIbi_9uVGR_1L7wo5cuBPA
Username: raun@gmail.com


### ------------------------------------------------------------------------------------------- ###

### PRODUCT ### create product
POST http://localhost:3000/api/v1/product/create/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWNkNzY3YzY0YTIwNTBkMDBlNTJiMmEiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkyMTc2Mjg0LCJleHAiOjE1OTIxNzYzMDQsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.yLJGGCsRZLqeMpvUL0Ab_1UQ9DjaY8PJva5VNobhxoMgli1jA4DWXCM8KZC4tgHZgotmyapoHGRdovWYeaoFBA
Username: raun@gmail.com

 {
	"product": {
        "name": "Gauri Tezz Milk",
        "description": "Fresh 'n' Natural",
        "priceTaxIncl": "75.0",
        "vendor": "5ecd767c64a2050d00e52b2a",
        "slug": "gau-tezz-milk",
        "society": [{
            "_id": "5ed93841bd7a4d1db48ba7d0"
        }]
	}
}

### PRODUCT ### get all products
GET http://localhost:3000/api/v1/product?vendor=5ecd767c64a2050d00e52b2a
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVlYzk5OWY2MDUxOTA1M2Q4YzdmZjViOSIsImlhdCI6MTU5MDQxNTkyNywiZXhwIjoxNTkwNDE1OTQ3LCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.KKkTkAdXlqjSIaHNnUVbWfvpNFiEQWvAYIGmUV9dG2ouCqieyzKyygAujtcZySVTv8jKtPOhQ3uod0nG8gTqTg
Username: raun@gmail.com

### PRODUCT ### get product by id
GET http://localhost:3000/api/v1/product/5ee4d9d50c8d771404a40ff8
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWNkNzY3YzY0YTIwNTBkMDBlNTJiMmEiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkyMDgxMzM2LCJleHAiOjE1OTIwODEzNTYsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.GsnBJP3IvwtkP2S8BLHQ-AVL3gFWGS6eYe3PRfs8jpiZ4NnN-uDfie5717uWK1AC9LWHwSWA5SMftrr2Ih0CBA
Username: raun@gmail.com

### PRODUCT ### update product by id
PUT http://localhost:3000/api/v1/product/update/5ee5bcea1e53c249783f7357
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWNkNzY3YzY0YTIwNTBkMDBlNTJiMmEiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkyMzI1MzY0LCJleHAiOjE1OTIzMjUzODQsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.WAg3S-I7xd6kJ323Aj6lRHlYKJYESt1o5X85UenUb_BjZny9LIE5dlwaIeZOIM5DJ9bEr1ezLEnTRSt0ppNBcA
Username: raun@gmail.com

{
	"product": {
        "_id" : "5ee5bcea1e53c249783f7357",
        "name": "Gau Tezz Milk"
	}
}


### ------------------------------------------------------------------------------------------- ###

### LOCATION ### create location
POST http://localhost:3000/api/v1/location/create/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVlYzk5OWY2MDUxOTA1M2Q4YzdmZjViOSIsImlhdCI6MTU5MDQxNTkyNywiZXhwIjoxNTkwNDE1OTQ3LCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.KKkTkAdXlqjSIaHNnUVbWfvpNFiEQWvAYIGmUV9dG2ouCqieyzKyygAujtcZySVTv8jKtPOhQ3uod0nG8gTqTg
Username: raun@gmail.com

{
    "location": {
        "name": "Udaipur",
        "parent": {
            "_id": "5f0aca7d85689940fc316181",
            "name": "Rajasthan"
            }  
	}
}

### LOCATION ### get location by parent id
GET http://localhost:3000/api/v1/location/parent/5eee00ee8ed1f82cd4e44616/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9pZCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVlYzk5OWY2MDUxOTA1M2Q4YzdmZjViOSIsImlhdCI6MTU5MDQxNTkyNywiZXhwIjoxNTkwNDE1OTQ3LCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.KKkTkAdXlqjSIaHNnUVbWfvpNFiEQWvAYIGmUV9dG2ouCqieyzKyygAujtcZySVTv8jKtPOhQ3uod0nG8gTqTg
Username: raun@gmail.com

### ------------------------------------------------------------------------------------------- ###


### ORDER ### create order
POST http://localhost:3000/api/v1/order/create/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWVkMWE2ZjdmYzE3YjA4MjQwZTlkMDIiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTk0NDU3OTQwLCJleHAiOjE1OTQ0NTc5NjAsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.OB9wExy94-GHaPUvETXlAAXHNMI57MLfDSAlYWYHT1-l9gtxBXg24iS102pMqGDGJtD4SUMGs-KLML1pZrHRlQ
Username: rishimehta365@gmail.com

 {
	"order": {
        "slug": "milk-order",
        "customer": "5f0a15f74d67874c98a85593",
        "vendor": "5effa45ae5188404ac81e20b",
        "product": "5f09c44b3c87778e1aca0ccf",
        "price": "45.5",
        "discount": "0.5",
        "cart": "1.5",
        "status": {
            "name": "Shipped",
            "color": "pink-500",
            "date" : "2018/03/31 03:01:12"
        }
	}
}

### ORDER ### get all orders by vendor id
GET http://localhost:3000/api/v1/order?vendor=5effa45ae5188404ac81e20b
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVmMDBjYzRkNDFmM2YyM2VjYzlhZGZiYSIsInJvbGVzIjoiY3VzdG9tZXIiLCJwZXJtaXNzaW9ucyI6WyJyZWFkIl0sImlhdCI6MTU5Mzg4ODI5MywiZXhwIjoxNTkzODg4MzEzLCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.sFmb1UwvMRcEqu8mj5nkHyR_EK7yVbEN_r_GmozUDi8Zmq9L7uiXGvaK0aOpO7ry0OidIYOTVqEEH8NyP7sH7A
Username: vendor@gmail.com

### ORDER ### get order by id
GET http://localhost:3000/api/v1/order/5f09b0fbb3003742e89c5524
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmRvckBnbWFpbC5jb20iLCJpZCI6IjVmMDBjYzRkNDFmM2YyM2VjYzlhZGZiYSIsInJvbGVzIjoiY3VzdG9tZXIiLCJwZXJtaXNzaW9ucyI6WyJyZWFkIl0sImlhdCI6MTU5Mzg4ODI5MywiZXhwIjoxNTkzODg4MzEzLCJhdWQiOiJDbGllbnRfSWRlbnRpdHkiLCJpc3MiOiJBdXRob3JpemF0aW9uL1Jlc291cmNlL1RoaXMgc2VydmVyIiwic3ViIjoidmVuZG9yQGdtYWlsLmNvbSJ9.sFmb1UwvMRcEqu8mj5nkHyR_EK7yVbEN_r_GmozUDi8Zmq9L7uiXGvaK0aOpO7ry0OidIYOTVqEEH8NyP7sH7A
Username: vendor@gmail.com


### ------------------------------------------------------------------------------------------- ###

### VENDOR ### PUB SUB
GET http://localhost:3000/api/v1/vendor/pub
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdW5AZ21haWwuY29tIiwiaWQiOiI1ZWVkMWE2ZjdmYzE3YjA4MjQwZTlkMDIiLCJyb2xlcyI6InZlbmRvciIsInBlcm1pc3Npb25zIjpbInJlYWQiXSwiaWF0IjoxNTkzODE2NjEwLCJleHAiOjE1OTM4MTY2MzAsImF1ZCI6IkNsaWVudF9JZGVudGl0eSIsImlzcyI6IkF1dGhvcml6YXRpb24vUmVzb3VyY2UvVGhpcyBzZXJ2ZXIiLCJzdWIiOiJyYXVuQGdtYWlsLmNvbSJ9.ucV35w2UMyHT8gZrl9yOrIeNwKabekPZn0_B_ZXYijxr_FYQ_A5Zh01euMFfZH_YkRNxhSfeT2KPR3Fazz7dQQ
Username: raun@gmail.com

### ------------------------------------------------------------------------------------------- ###